import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Header } from '../src/components/Header'

import { Navbar } from '../src/components/Navbar'

export interface toggleThemeType {
  toggleTheme(): void,
  title: string
}

export default function Home({ toggleTheme, title }: toggleThemeType) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>

      <Header toggleTheme={toggleTheme} title={title} />
      <Navbar />

    </div>
  )
}